const ACTION = {
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  ADD_ITEM_SALE_CART: "ADD_ITEM_SALE_CART",
  SALE_CART_STATUS: "SALE_CART_STATUS",
  RESET_SALE_CART: "RESET_SALE_CART",
  ADD_DISCOUNT_SALE: "ADD_DISCOUNT_SALE",
  SALE_DEATILS: "SALE_DEATILS",
  SALE_TRANSACTIONS: "SALE_TRANSACTIONS",

  PURCHASE_TRANSACTIONS: "PURCHASE_TRANSACTIONS",
  PURCHASE_DEATILS: "PURCHASE_DEATILS",

  BUSINESS_CREATE_SUCCESS: "BUSINESS_CREATE_SUCCESS",
  BUSINESS_MODIFY_SUCCESS: "BUSINESS_MODIFY_SUCCESS",
  BUSINESS_DELETE_SUCCESS: "BUSINESS_DELETE_SUCCESS",
  BUSINESS_GET_SUCCESS: "BUSINESS_GET_SUCCESS",

  CUSTOMER_GET_SUCCESS: "CUSTOMER_GET_SUCCESS",
  CUSTOMER_LEDGER_GET_SUCCESS: "CUSTOMER_LEDGER_GET_SUCCESS",
  CUSTOMER_HISTORY: "CUSTOMER_HISTORY",

  SUPPLIER_GET_SUCCESS: "SUPPLIER_GET_SUCCESS",
  SUPPLIER_HISTORY: "SUPPLIER_HISTORY",
  SUPPLIER_LEDGER_GET_SUCCESS: "SUPPLIER_LEDGER_GET_SUCCESS",

  ADD_ITEM_PURCHASE_CART: "ADD_ITEM_PURCHASE_CART",
  PURCHASE_CART_STATUS: "PURCHASE_CART_STATUS",
  ADD_DISCOUNT_PURCHASE: "ADD_DISCOUNT_PURCHASE",

  EXPENSE_TRANSACTION_GET: "EXPENSE_TRANSACTION_GET",
  EXPENSE_CATEGORIES_GET: "EXPENSE_CATEGORIES_GET",
  EXPENSE_CATEGORIES_TRANSACTION_GET: "EXPENSE_CATEGORIES_TRANSACTION_GET",

  PRODUCT_GET_SUCCESS: "PRODUCT_GET_SUCCESS",
  PRODUCT_STOCK: "PRODUCT_STOCK",

  RESET_PURCHASE_CART: "RESET_PURCHASE_CART",

  PAYMENT_GET_SUCCESS: "PAYMENT_GET_SUCCESS:",
  RECEIPT_GET_SUCCESS: "RECEIPT_GET_SUCCESS",
  RECEIPT_GET: "RECEIPT_GET",

  SET_ALERT: "SET_ALERT",
  ERROR: "ERROR",

  TOKEN: "TOKEN",
  TOKEN_STATUS: "TOKEN_STATUS",
  LOADING: "LOADING",

  EMPLOYEES_GET: "EMPLOYEES_GET",
  TRANSACTIONS_GET: "TRANSACTIONS_GET",
  EMPLOYEE_TRANSACTION_GET: "EMPLOYEE_TRANSACTION_GET",

  USER_GET: "USER_GET",
  USERS_GET: "USERS_GET",
  OWNER: "OWNER",

  LANGUAGE: "LANGUAGE",

  SALE_REPORT: "SALE_REPORT",
  PURCHASE_REPORT: "PURCHASE_REPORT",
  PURCHASE_DEATIL_REPORT: "PURCHASE_DEATIL_REPORT",
  SALE_DEATIL_REPORT: "SALE_DEATIL_REPORT",
  EXPENSE_REPORT: "EXPENSE_REPORT",
  EMPLOYEE_REPORT: "EMPLOYEE_REPORT",
  PROFIT_LOSS: "PROFIT_LOSS",
  RESET_STATE: "RESET_STATE",
  USER_STATUS: "USER_STATUS",
  DAYBOOK: "DAYBOOK",
  CASHBOOK: "CASHBOOK",
  NOTIFICATIONS: "NOTIFICATIONS",

  NEW_USER: "NEW_USER",

  NON_INVENTORY_PRODUCT: "NON_INVENTORY_PRODUCT",
};

export default ACTION;
