import constants from './constants';

const urdu = {
  PRICE: 'قیمت',
  STOCK: 'اسٹاک',
  EMPTY_LIST: 'کوئی مواد نہیں',
  TOTAL_ITEM: 'کل آئٹم',
  SEARCH: 'تلاش کریں',

  VERFICATION_CODE: 'تصدیقی کوڈ',
  NEW_PASSWORD: 'نیا پاسورڈ',
  CONFIRM_PASSWORD: 'پاسورڈ کی تصدیق کریں',
  CHANGE_PASSWORD: 'پاسورڈ تبدیل کریں',
  EMAIL: 'ای میل',
  SEND_EMAIL: 'ای میل بھیجیں',
  PASSWORD: 'پاس ورڈ',
  FORGOT_PASSWORD: 'پاسورڈ بھول گے؟',
  NO_ACCOUNT: 'اکاؤنٹ نہیں ہے؟ ابھی سائن اپ کریں',
  POLICY:
    'سائن اپ پر کلک کرکے ، آپ ہماری شرائط ، ڈیٹا پالیسی سے اتفاق کرتے ہیں',
  SIGN_UP: 'سائن اپ',
  SIGN_IN: 'سائن ان',
  RESEND_CODE: 'توثیقی کوڈ آپ کے فراہم کردہ ای میل پتے پر بھیج دیا گیا ہے ، اگر آپ کو توثیقی کوڈ نہیں ملا ہے تو دوبارہ بھیجنے کے لئے یہاں کلک کریں',
  VERFICATION: 'تصدیق',
  USER_NAME: 'صارف کا نام',
  NAME: 'نام',
  PHONE_NUMBER: 'فون نمبر',
  ADDRESS: 'پتہ',
  OPENING_BALANCE: 'افتتاحی بقایا',
  ENTER_REQUIRED_FIELDS: 'براہ کرم مطلوبہ فیلڈز درج کریں',
  ENTER_VALID_EMAIL: 'برائے مہربانی قابل قبول ای میل ایریس لکھیں',
  YOU_SURE: 'کیا آپ واقعی اس عمل کے لئے یقینی ہیں؟',
  SAVE: 'محفوظ کریں',

  DELETE: 'اسے مٹا دو',
  AMOUNT: 'رقم',
  DATE: 'تاریخ',
  CUSTOMER: 'گاهک',
  DESCRIPTION: 'تفصیل',
  GENERATE_RECEIPT: 'رسید بنائیں',

  RECEIPTS: 'رسیدیں',
  FILTERS: 'فلٹرز',
  RECEIVABLE: 'قابل وصول',
  ALL: 'تمام',
  PAYABLE: 'قابل ادائیگی',
  BALANCE: 'بقیہ',
  CUSTOMERS: 'گاہکوں',
  UPDATE_CUSTOMER: 'کسٹمر کی معلومات کو اپ ڈیٹ کریں',
  ADD_CUSTOMER: 'کسٹمر شامل کریں',
  UPDATE_RECEIPT: 'رسید کی معلومات کو اپ ڈیٹ کریں',
  ADD_RECEIPT: 'رسید شامل کریں',
  RECEIPT: 'رسید',

  FILTER: 'فلٹر کریں',
  FILTER_TYPE: 'فلٹر کی قسم',
  MONTH: 'مہینہ',

  SALE: 'فروخت',
  PURCHASES: 'خریداری',
  PRODUCTS_SERVICES: 'مصنوعات / خدمات',
  SUPPLIERS: 'سپلائر',
  EMPLOYEES: 'ملازمین',
  EXPENSES: 'اخراجات',

  LOGO: 'لوگو',
  ENGLISH: 'انگریزی',
  URDU: 'اردو',
  BUSINESS: 'کاروبار',
  USERS: 'صارفین',
  OWNER: 'مالک',
  SET_LANGUAGE: 'زبان مرتب کریں',
  SET_PRICE_UNIT: 'پرائس یونٹ مقرر کریں',
  LOGOUT: 'لاگ آوٹ',

  FULL_NAME: 'پورا نام',
  CURRENT_PASSWORD: 'موجود پاسورڈ',
  SETTINGS: 'ترتیبات',
  ADD_USER: 'صارف شامل کریں',
  UPDATE_USER: 'صارف کی معلومات کو اپ ڈیٹ کریں',

  CONFIRM: 'تصدیق کریں',
  CANCEL: 'منسوخ کریں',
  OK: 'ٹھیک ہے',

  SALARY: 'تنخوا',
  EXTRA_EARNINGS: 'اضافی آمدنی (ملازم اکاؤنٹ میں شامل کریں)',
  RETURN_BY_EMPLOYEE: 'رسیدیں (ملازم کے ذریعہ واپس)',
  CASH_PAYMENT: 'نقد ادائیگی (ملازمین کو ادائیگی)',
  SALARY_EA: 'تنخواہ (ملازم اکاؤنٹ میں شامل کریں))',
  EMPLOYEE: 'ملازم',
  TYPE: 'قسم',
  TRANSACTIONS: 'لین دین',
  PROCESS_SALARIES: 'تنخواہیں بنائیں',
  PROCESS: 'بنائیں',
  SALARIES_NOTE:
    'نوٹ: براہ کرم نوٹ کریں کہ یہ ملازمین کیش ادائیگی نہیں ہے۔ اس رقم کو ملازم لیگر میں شامل کیا جائے گا',

  ADD_EMPLOYEE: 'ملازم شامل کریں',
  UPDATE_EMPLOYEE: 'ملازم کو اپ ڈیٹ کریں',
  ADD_TRANSACTION: 'ٹرانزیکشن شامل کریں',
  UPDATE_TRANSACTION: 'ٹرانزیکشن اپ ڈیٹ',

  EXPENSE_CATEGORY_NAME: 'اخراجات کی قسم کا نام',
  CATAGORY: 'قسم',
  TOTAL_EXPENSE: 'کل اخراجات',
  EXPENSE_TRANSACTIONS: 'اخراجات کے لین دین',
  ADD_EXPENSE: 'اخراجات شامل کریں',
  UPDATE_EXPENSE: 'اخراجات کی معلومات کو اپ ڈیٹ کریں',
  ADD_EXPENSE_CATEGORY: 'اخراجات کی قسم شامل کریں',
  UPDATE_EXPENSE_CATEGORY: 'اخراجات کے زمرے کی معلومات کو اپ ڈیٹ کریں',

  OUT_OF_STOCK: 'زخیرے سے باہر',
  STOCK_LESS_THAN: 'اس سے کم اسٹاک',
  PURCHAE_PRICE: 'قیمت خرید',
  OPENING_STOCK: 'افتتاحی اسٹاک',
  SALE_PRICE: 'قیمت فروخت',
  TOTAL_STOCK: 'کل اسٹاک',
  COST_PRICE: 'لاگت کی قیمت',

  ADD_Product_Service: 'پروڈکٹ / سروس شامل کریں',
  Update_Product_Service: 'پروڈکٹ / سروس کو اپ ڈیٹ کریں',
  TOTAL_AMOUNT: 'کل رقم',
  DISCOUNT: 'چھوٹ',
  NET_AMOUNT: 'اصل رقم',
  SUPPLIER: 'سپلائر',
  AMOUNT_PAID: 'ادا شدہ رقم',
  PURCHASE: 'خریداری',
  PAID: 'ادا کیا',
  PURCHASE_TRANSACTIONS: 'خریداری کے لین دین',
  PURCHASE_DETAILS: 'خریداری کی تفصیلات',
  PURCHASE_RETURN: 'خریداری کی واپسی',
  CHECKOUT: 'جانچ پڑتال',
  TOTAL: 'کل',
  ADD_DISCOUNT: 'چھوٹ دیں',
  NET_TOTAL: 'نیٹ ٹوٹل',

  ADD_TO_CART: 'ٹوکری میں شامل کریں',
  PAID_TOTAL_AMOUNT_SHOULD_EQUAL: 'ادا شدہ رقم کل رقم کے برابر ہونی چاہئے',
  NEW_CUSTOMER: 'نیا گاہک',
  GENRATE_QUOTATION: 'کوٹیشن بنائیں',
  GENRATE_BILL: 'بل تیار کریں',

  SALE_DETAILS: 'فروخت کی تفصیلات',
  SALE_RETURN: 'سیل ریٹرن',
  SALE_TRANSACTIONS: 'فروخت کے لین دین',
  ADD_NON_INVENTORY_ITEM: 'غیر انوینٹری آئٹم شامل کریں',
  BILL: 'بل',
  QUOTATION: 'کوٹیشن',

  ADD_SUCCESS: 'کامیابی کے ساتھ شامل کیا گیا',
  UPDATE_SUCCESS: 'کامیابی کے ساتھ اپ ڈیٹ ہوا',
  DELETE_SUCCESS: 'کامیابی کے ساتھ حذف ہوا',
  SERVER_ERROR: 'کچھ غلط ہو گیا. براہ کرم دوبارہ لوڈ کریں',
  SALARIES_PROCESSED: 'ملازمین کے کھاتے میں تنخواہیں شامل کردی گئیں',

  STOCK_NOT_AVALIABLE: 'اسٹاک دستیاب نہیں ہے',
  VERFICATION_CODE_SENT: 'توثیقی کوڈ ای میل ایڈریس پر بھیجا گیا',
  PASSWORD_CHANGE_SUCCESS: 'کامیابی کے ساتھ پاس ورڈ تبدیل ہوگیا',
  SIGNUP_SUCCESS: 'سائن اپ ہو گیا',
  LOGOUT_SUCCESS: 'کامیابی کے ساتھ لاگ آؤٹ ہوا',
  PAYMENTS: 'ادائیگی',
  ADD_PAYMENT: 'ادائیگی شامل کریں',
  UPDATE_PAYMENT: 'ادائیگی کی تازہ کاری کریں',
  ADD_SUPPLIER: 'سپلائر شامل کریں',
  UPDATE_SUPPLIER: 'اپ ڈیٹ سپلائر',

  PASSWORD_CPASSWORD_SAME: 'پاس ورڈ اور تصدیق پاس ورڈ ایک ہی ہونا چاہئے',
  ENTER_SECURE_PASSWORD: 'براہ کرم ایک محفوظ پاس ورڈ درج کریں',

  SALE_REPORT: 'فروخت رپورٹ',
  REPORTS: 'رپورٹیں',
  START_DATE: 'شروع کرنے کی تاریخ',
  END_DATE: 'آخری تاریخ',
  QTY: 'مقدار',

  QUANTITY: 'مقدار',
  COST: 'لاگت',
  PURCHASE_DETAIL: 'خریداری کا تفصیل',
  PURCHASE_REPORT: 'خریداری کی رپورٹ',
  SALE_DETAIL: 'فروخت کی تفصیل',
  EXPENSE_REPORT: 'اخراجات کی رپورٹ',
  EXPENSE: 'خرچہ',
  EMPLOYEE_REPORT: 'ملازمین کی رپورٹ',
  PROFIT_LOSS_STATEMENT: 'تفصیل برائے نفع و نقصان',
  COSTING: 'قیمت',
  GROSS_PROFIT: 'کل منافع',
  NET_PROFIT: 'خالص منافع',
  CUSTOMER_CARE: 'صارفین کی سہولت',
  RATE_THIS_APP: 'اس ایپ کی درجہ بندی کریں',
  TUTORIAL: 'سبق',
  PAYMENT: 'ادائیگی',
  VERSION: 'ورژن',
  PHONE_INVALID: 'فون نمبر درست نہیں',
  WHATSAPP: 'Whatsapp',
  SMS: 'SMS',
  NO_PERMISSION: 'معذرت ، کیمرے کی اجازت ضروری ہے',
  FILE_TOO_LARGE: 'تصویر کا سائز بہت بڑا ہے',
  DAYBOOK: 'دن کی کتاب',
  PURCHASE_CASH: 'خریداری کیش',
  PURCHASE_CREDIT: 'خریداری کریڈٹ',
  PURCHASE_TOTAL: 'کل خرید',
  SALE_CASH: 'کیش سیل',
  SALE_CREDIT: 'کریڈٹ سیل',
  SALE_TOTAL: 'کل فروخت',
  OPENING_CASH: 'افتتاحی نقد رقم',
  COST_OF_GOODS: 'سامان خریدنے کی قیمت',
  CLOSING_BALANCE: 'اختتامی توازن',
  CASHBOOK: 'کيش بک',
  OPENING_CASH: 'افتتاحی کیش',
  CREDIT: 'کریڈٹ',
  DEBIT: 'ڈیبٹ',
  TOTAL_AMOUNT_PAID_EMPLOYEES: 'ملازمین کو ادا کی جانے والی کل رقم',
  TOTAL_AMOUNT_EARNED_EMPLOYEES: 'ملازمین کے ذریعہ کمائی جانے والی کل رق',
  TOTAL_DEBIT: 'کل ڈیبٹ',
  TOTAL_CREDIT: 'کل کریڈٹ',
  NEXT: 'اگلے',
  NOTIFICATION: 'اطلاع',
  CLOSE: 'بند کریں',
  SERVICE: 'خدمت',
  PRODUCT: 'پروڈکٹ',
  PLEASE_TURN_ON_WIFI_OR_DATA_NETWORK:
    'براہ کرم وائی فائی یا ڈیٹا نیٹ ورک کو آن کریں',
  COST_VALUE: 'اسٹاک کی قیمت',
  SALE_VALUE: 'اسٹاک کی فروخت قیمت',
  SALE_PRICE_SHOULD_BE_GREATER: 'فروخت کی قیمت خرید قیمت سے زیادہ ہونی چاہئے',
  OPENING_BALANCE_TYPE: 'بیلنس کھولنے کی قسم',
  SALE_DISCOUNT: 'فروخت چھوٹ',
  PURCHASE_DISCOUNT: 'خریداری چھوٹ',
  INVENTORY_ITEMS: 'انوینٹری آئٹمز',
  NON_INVENTORY_ITEMS: 'غیر انوینٹری اشیاء',

  ADD_LOAN: 'اودھر شامل کریں',
  EDIT_LOAN: 'اودھر کو اپ ڈیٹ کریں',

  BANK: 'بینک',
  BANKS: 'بینک',
  ADD_BANK: 'بینک شامل کریں',
  ACCOUNT_NUMBER: 'اکاؤنٹ نمبر',
  UPDATE_BANK: 'بینک کو اپ ڈیٹ کریں',
  BANK_TRANSACTIONS: 'بینک ٹرانزیکشن',
  TRANSACTION_TYPE: 'ٹرانزیکشن کی قسم',
  REDUCE_BANK: 'بینک بیلنس کو کم کریں',
  INCREASE_BANK: 'بینک بیلنس میں اضافہ کریں',
  BANK_DEPOSIT: 'بینک ڈپازٹ',
  BANK_WITHDRAW: 'رقم نکلوانا',
  TRANSFER_CASH_TO_BANK: 'بینک میں نقد رقم منتقل کریں',
  TRANSFER_BANK_TO_CASH: 'بینک سے نقد رقم منتقل کریں',
  BANK_BALANCE: 'بینک بیلنس',
  BALANCE_SHEET: 'بیلنس شیٹ',
  BANK_STATEMENT: 'بینک اسٹیٹمنٹ',
  CUSTOMERS_REPORT: 'صارفین کی رپورٹ',
  SUPPLIERS_REPORT: 'سپلائرز کی رپورٹ',
  STOCK_SUMMARY: 'اسٹاک کا خلاصہ',

  BARCODE_READER: 'بارکوڈ ریڈر',
  BAR_CODE: 'بارکوڈ',
  NO_PRODUCT_FOUND: 'کوئی مصنوعہ نہیں ملا',

  MYSTORE: 'میرا آن لائن اسٹور',
  MAKEBUSSINESSONLINE: 'ای حساب کے ذریعہ اپنے کاروبار کو آن لائن بنائیں',
  YOURSTORE: 'آپ کا آن لائن اسٹور',
  COMINGSOON: 'جلد آرہا ہے',

  STORE: 'اسٹور',
  EDIT_BUSSINESS_INFO: 'کاروبار کی معلومات میں ترمیم کریں',
  ADD_PRODUCTS_STORE: 'ذخیرہ کرنے کے لئے مصنوعات شامل کریں',
  ADD_TO_STORE: 'اسٹور میں شامل کریں',
  DISPLAY_IN_STORE: 'آن لائن اسٹور میں دکھائیں',
  OPEN_SALE: 'اوپن سیل',
  STORE_NAME: 'اسٹور کا نام',
  CATEGORY: 'قسم',
  ORDERS: 'احکامات',
  REJECT_ORDER: 'حکم مسترد کریں',
  ACCEPT_ORDER: 'آرڈر قبول کریں',

  NON_INVENTORY_SALE_ALRET: 'ٹوکری میں کوئی اشیاء نہیں۔ اس فروخت سے انوینٹری نہیں بدلے گی',
  NON_INVENTORY_SALE: 'غیر انوینٹری فروخت',
  NON_INVENTORY_PURCHASE_ALRET: 'ٹوکری میں کوئی اشیاء نہیں۔ اس خریداری سے انوینٹری تبدیل نہیں ہوگی',
  NON_INVENTORY_PURCHASE: 'غیر انوینٹری خریداری',

  DASHBOARD: 'ڈیش بورڈ',
  BANKBALANCE: 'بینک بیلنس',
  BESTSALEINGPRODUCTS: 'بہترین فروخت ہونے والی مصنوعات',
  CASHINHAND: 'نقد',
  PAYABLES: 'ادائیگی',
  ADDED_TO_CART: 'ٹوکری میں شامل',
  GOOGLE_STORE_NOT_AVALIABLE: "گوگل پلے اسٹور دستیاب نہیں ہے",
  APP_STORE_NOT_AVALIABLE: "ایپ اسٹور دستیاب نہیں ہے",
  IMAGE: "تصویر",
  ONLINE_STORE_NAME: "",
  OPEN_IMAGE_PICKER: "تصویری گیلری",
  OPEN_CAMERA: "کیمرا کھلا",
  SELECT: "منتخب کریں"

};

const english = {
  PRICE: 'Price',
  STOCK: 'Stock',
  EMPTY_LIST: 'No Data',
  TOTAL_ITEM: 'Item(s)',
  SEARCH: 'Search',

  VERFICATION_CODE: 'Verification Code',
  NEW_PASSWORD: 'New Password',
  CONFIRM_PASSWORD: 'Confirm Password',
  CHANGE_PASSWORD: 'Change Password',
  EMAIL: 'Email',
  SEND_EMAIL: 'Send Email',
  PASSWORD: 'Password',
  FORGOT_PASSWORD: 'Forgot Password?',
  NO_ACCOUNT: "Don't Have Account? Sign Up Now",
  POLICY: 'By clicking Sign Up, you agree to our Terms, Data Policy ',
  SIGN_UP: 'Sign Up',
  SIGN_IN: 'Sign in',
  RESEND_CODE: "Verification code has been sent to your provided email address, If you haven't received the verification code click here to send again",
  VERFICATION: 'Verification',
  USER_NAME: 'User Name',

  NAME: 'Name',
  PHONE_NUMBER: 'Phone Number',
  ADDRESS: 'Address',
  OPENING_BALANCE: 'Opening Balance',
  ENTER_REQUIRED_FIELDS: 'Please Enter Required Fields',
  ENTER_VALID_EMAIL: 'Please Enter A Valid Email Address',
  YOU_SURE: 'Are you Sure?',
  SAVE: 'Save',

  DELETE: 'Delete',
  AMOUNT: 'Amount',
  DATE: 'Date',
  CUSTOMER: 'Customer',
  DESCRIPTION: 'Description',
  GENERATE_RECEIPT: 'Generate Receipt',

  RECEIPTS: 'Receipts',
  FILTERS: 'Filters',
  RECEIVABLE: 'Receivable',
  ALL: 'All',
  PAYABLE: 'Payable',
  BALANCE: 'Balance',
  CUSTOMERS: 'Customers',
  UPDATE_CUSTOMER: 'Update Customer',
  ADD_CUSTOMER: 'Add Customer',
  UPDATE_RECEIPT: 'Update Receipt',
  ADD_RECEIPT: 'Add Receipt',
  RECEIPT: 'Receipt',

  FILTER: 'Filter',
  FILTER_TYPE: 'Filter Type',
  MONTH: 'Month',

  SALE: 'Sale',
  PURCHASES: 'Purchases',
  PRODUCTS_SERVICES: 'Products/Services',
  SUPPLIERS: 'Suppliers',
  EMPLOYEES: 'Employees',
  EXPENSES: 'Expenses',

  LOGO: 'Logo',
  ENGLISH: 'English',
  URDU: 'Urdu',
  BUSINESS: 'Business',
  USERS: 'Users',
  OWNER: 'Owner',
  SET_LANGUAGE: 'Set Language',
  SET_PRICE_UNIT: 'Set Price Unit',
  LOGOUT: 'Log Out',

  FULL_NAME: 'Full Name',
  CURRENT_PASSWORD: 'Current Password',
  SETTINGS: 'Settings',
  ADD_USER: 'Add User',
  UPDATE_USER: 'Update User',

  CONFIRM: 'Confirm',
  CANCEL: 'Cancel',
  OK: 'Ok',
  SALARY: 'Salary',
  EXTRA_EARNINGS: 'Extra Earnings (Add to Employee Account)',
  RETURN_BY_EMPLOYEE: 'Receipts (Return By Employee)',
  CASH_PAYMENT: 'Cash Payment (Pay to Employee)',
  SALARY_EA: 'Salary (Add to Employee Account)',
  EMPLOYEE: 'Employee',
  TYPE: 'Type',
  TRANSACTIONS: 'Transactions',
  PROCESS_SALARIES: 'Process Salaries',
  PROCESS: 'Process',
  SALARIES_NOTE:
    'Note: Please Note this is not Employee Cash Payment. This Amount will be added to Employee Account (leager)',
  ADD_EMPLOYEE: 'Add Employee',
  UPDATE_EMPLOYEE: 'Update Employee',
  ADD_TRANSACTION: 'Add Transaction',
  UPDATE_TRANSACTION: 'Update Transaction',
  EXPENSE_CATEGORY_NAME: 'Expense Category Name',
  CATAGORY: 'Category',
  TOTAL_EXPENSE: 'Total Expense',
  EXPENSE_TRANSACTIONS: 'Expense Transactions',
  ADD_EXPENSE: 'Add Expense',
  UPDATE_EXPENSE: 'Update Expense',
  ADD_EXPENSE_CATEGORY: 'Add Expense Category',
  UPDATE_EXPENSE_CATEGORY: 'Update Expense Category',

  OUT_OF_STOCK: 'Out of Stock',
  STOCK_LESS_THAN: 'Stock Less Than',
  PURCHAE_PRICE: 'Purchase Price',
  OPENING_STOCK: 'Opening Stock',
  SALE_PRICE: 'Sale Price',
  TOTAL_STOCK: 'Total Stock',
  COST_PRICE: 'Cost Price',

  ADD_Product_Service: 'Add Product/Service',
  UPDATE_PRODUCT_SERVICE: 'Update Product/Service',
  TOTAL_AMOUNT: 'Total Amount',
  DISCOUNT: 'Discount',
  NET_AMOUNT: 'Net Amount',
  SUPPLIER: 'Supplier',
  AMOUNT_PAID: 'Amount Paid',
  PURCHASE: 'Purchase',
  PAID: 'Paid',
  PURCHASE_TRANSACTIONS: 'Purchase Transactions',
  PURCHASE_DETAILS: 'Purchase Details',
  PURCHASE_RETURN: 'Purchase Return',
  CHECKOUT: 'Checkout',
  TOTAL: 'Total',
  ADD_DISCOUNT: 'Add Discount',
  NET_TOTAL: 'Net Total',
  ADD_TO_CART: 'Add to Cart',
  PAID_TOTAL_AMOUNT_SHOULD_EQUAL:
    'Paid Amount Should be Equal to Total Amount ',
  NEW_CUSTOMER: 'New Customer',
  GENRATE_QUOTATION: 'Generate Quotation',
  GENRATE_BILL: 'Generate Bill',
  SALE_DETAILS: 'Sale Details',
  SALE_RETURN: 'Sale Return',
  SALE_TRANSACTIONS: 'Sale Transactions',
  ADD_NON_INVENTORY_ITEM: 'Add Non Inventory Item',
  BILL: 'Bill',
  QUOTATION: 'Quotation',

  ADD_SUCCESS: 'Added Successfully',
  UPDATE_SUCCESS: 'Updated Successfully',
  DELETE_SUCCESS: 'Deleted Successfully',
  SERVER_ERROR: 'Something Went Wrong. Please Reload',
  SALARIES_PROCESSED: 'Salaries Added to Employee Account',

  STOCK_NOT_AVALIABLE: 'Stock Not Available',
  VERFICATION_CODE_SENT: 'Verification Code Sent to Email Address',
  PASSWORD_CHANGE_SUCCESS: 'Password Changed Successfully',
  SIGNUP_SUCCESS: 'Sign Up Successfull',
  LOGOUT_SUCCESS: 'Logout Successfully',

  PAYMENTS: 'Payments',
  ADD_PAYMENT: 'Add Payment',
  UPDATE_PAYMENT: 'Update Payment',
  ADD_SUPPLIER: 'Add Supplier',
  UPDATE_SUPPLIER: 'Update Supplier',

  PASSWORD_CPASSWORD_SAME: 'Password and Confirm Password Should be Same',
  ENTER_SECURE_PASSWORD:
    'Password Should contain [1-9] [a-z] and should be 8 letters long',
  SALE_REPORT: 'Sale Report',
  REPORTS: 'Reports',
  START_DATE: 'Start Date',
  END_DATE: 'End Date',
  QUANTITY: 'Quantity',
  COST: 'Cost',
  PURCHASE_DETAIL: 'Purchase Detail',
  PURCHASE_REPORT: 'Purchase Report',
  SALE_DETAIL: 'Sale Detail',
  EXPENSE_REPORT: 'Expense Report',
  EXPENSE: 'Expense',
  EMPLOYEE_REPORT: 'Employee Report',
  PROFIT_LOSS_STATEMENT: 'Profit and Loss Statement',
  COSTING: 'Costing',
  GROSS_PROFIT: 'Gross Profit',
  NET_PROFIT: 'Net Profit',
  CUSTOMER_CARE: 'Customer Care',
  RATE_THIS_APP: 'Rate this App',
  TUTORIAL: 'Tutorials',
  PAYMENT: 'Payment',
  VERSION: 'Version',
  PHONE_INVALID: 'Phone Number not Valid',
  WHATSAPP: 'Whatsapp',
  SMS: 'SMS',
  NO_PERMISSION: 'Sorry, Camera Roll Permission is Required',
  FILE_TOO_LARGE: 'Image Size is too large',
  DAYBOOK: 'Day Book',
  PURCHASE_CASH: 'Purchase Cash',
  PURCHASE_CREDIT: 'Purchase Credit',
  PURCHASE_TOTAL: 'Purchase Total',
  SALE_CASH: 'Sale Cash',
  SALE_CREDIT: 'Sale Credit',
  SALE_TOTAL: 'Sale Total',
  OPENING_CASH: 'OPENING_CASH',
  COST_OF_GOODS: 'Cost of Goods',
  CLOSING_BALANCE: 'Closing Balance',
  CASHBOOK: 'Cash Book',
  OPENING_CASH: 'Opening Cash',
  CREDIT: 'Credit',
  DEBIT: 'Debit',
  TOTAL_AMOUNT_PAID_EMPLOYEES: 'Total Amount Paid to Employees',
  TOTAL_AMOUNT_EARNED_EMPLOYEES: 'Total Amount Earned By Employees',
  TOTAL_DEBIT: 'Total Debit',
  TOTAL_CREDIT: 'Total Credit',
  NEXT: 'Next',
  NOTIFICATION: 'Notification',
  CLOSE: 'Close',
  SERVICE: 'Service',
  PRODUCT: 'Product',
  QTY: 'Qty',
  PLEASE_TURN_ON_WIFI_OR_DATA_NETWORK: 'Please Turn on Wifi or Data Network.',
  COST_VALUE: 'Cost Value',
  SALE_VALUE: 'Sale Value',
  SALE_PRICE_SHOULD_BE_GREATER:
    'Sale Price should be Greater then Purchase Price',
  OPENING_BALANCE_TYPE: 'Opening Balance Type',
  SALE_DISCOUNT: 'Sale Discount',
  PURCHASE_DISCOUNT: 'Purchase Discount',
  INVENTORY_ITEMS: 'Inventory Items',
  NON_INVENTORY_ITEMS: 'Non Inventory Items',
  ADD_LOAN: 'Add Customer Payment',
  EDIT_LOAN: 'Edit Customer Payment',

  BANK: 'Bank',
  BANKS: 'Banks',
  ADD_BANK: 'Add Bank',
  ACCOUNT_NUMBER: 'A/c Number',
  UPDATE_BANK: 'Update Bank',
  BANK_TRANSACTIONS: 'Bank Transactions',
  TRANSACTION_TYPE: 'Transaction Type',
  REDUCE_BANK: 'Reduce bank balance',
  INCREASE_BANK: 'Increase bank balance',
  BANK_DEPOSIT: 'Bank Deposit',
  BANK_WITHDRAW: 'Bank Withdrawal',
  TRANSFER_CASH_TO_BANK: 'Transfer cash to bank',
  TRANSFER_BANK_TO_CASH: 'Transfer from bank to cash',
  BANK_BALANCE: 'Bank Balance',
  BALANCE_SHEET: 'Balance Sheet',
  BANK_STATEMENT: 'Bank Statement',
  CUSTOMERS_REPORT: 'Customers Report',
  SUPPLIERS_REPORT: 'Suppliers Report',
  STOCK_SUMMARY: 'Stock Summary',

  BARCODE_READER: 'Barcode reader',
  BAR_CODE: 'Barcode',
  NO_PRODUCT_FOUND: 'No product found',
  MYSTORE: 'My Online Store',
  MAKEBUSSINESSONLINE: 'Take your business online with eHisaab',
  YOURSTORE: 'Your Online Store is',
  COMINGSOON: 'COMING SOON',

  STORE: 'Store',
  EDIT_BUSSINESS_INFO: 'Edit Bussiness info',
  ADD_PRODUCTS_STORE: 'Add products to store',
  ADD_TO_STORE: 'Add to store',
  DISPLAY_IN_STORE: 'Display in online store',
  OPEN_SALE: 'Open Sale',
  STORE_NAME: 'Store name',
  CATEGORY: 'Category',
  ORDERS: 'Orders',
  REJECT_ORDER: 'Reject order',
  ACCEPT_ORDER: 'Accept order',
  NON_INVENTORY_SALE_ALRET: 'No items in cart. This sale will not change inventory',
  NON_INVENTORY_SALE: 'Non-Inventory Sale',
  NON_INVENTORY_PURCHASE_ALRET: 'No items in cart. This purchase will not change inventory',
  NON_INVENTORY_PURCHASE: 'Non-Inventory Purchase',

  DASHBOARD: 'Dashboard',
  BANKBALANCE: 'Bank Balance',
  BESTSALEINGPRODUCTS: 'Best selling products',
  CASHINHAND: 'Cash in hand',
  PAYABLES: 'Payables',
  ADDED_TO_CART: 'Added to cart',
  GOOGLE_STORE_NOT_AVALIABLE: "Google Play Store not Available",
  APP_STORE_NOT_AVALIABLE: "App store not Available",
  IMAGE: "Image",
  ONLINE_STORE_NAME: "Online store name",
  OPEN_IMAGE_PICKER: "Open Gallery",
  OPEN_CAMERA: "Open Camera",
  SELECT: "Select"
};

export const getTranslation = (label, language) => {
  let translation = '';
  if (language == constants.URDU) {
    translation = urdu[label];
  } else {
    translation = english[label];
  }
  translation = translation == null ? label : translation;
  return translation;
};
